### ISSUE TITLE
Failed to import KernelInterface

### ISSUE THREAD

**Issue by conan19842002** [dfm/george#139]
I've got this error after installing the software from source (python setup.py install)
 ```
ImportError: cannot import name 'KernelInterface' from 'george.kernel_interface' (C:\Users\an.thanhnguyen\AppData\Local\Python-Eggs\Python-Eggs\Cache\george-0.3.1-py3.8-win-amd64.egg-tmp\george\kernel_interface.cp38-win_amd64.pyd)

```

**Comment by dfm** [comment]
Can you give more details about your system and environment setup and exactly which steps you took to install.

**Comment by conan19842002** [comment]
Thank you for quick response. Here are steps I have done:

- Clone the code:
```git clone https://github.com/dfm/george.git
```
- Install from source:
```
cd george
python setup.py install
```
- Try some code:
```
$python
>>> from george import kernels
```

Then got error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\an.thanhnguyen\Anaconda3\lib\site-packages\george-0.3.1-py3.8-win-amd64.egg\george\__init__.py", line 17, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\an.thanhnguyen\Anaconda3\lib\site-packages\george-0.3.1-py3.8-win-amd64.egg\george\kernels.py", line 27, in <module>
ImportError: cannot import name 'KernelInterface' from 'george.kernel_interface' (C:\Users\an.thanhnguyen\AppData\Local\Python-Eggs\Python-Eggs\Cache\george-0.3.1-py3.8-win-amd64.egg-tmp\george\kernel_interface.cp38-win_amd64.pyd)
>
```
