### ISSUE TITLE
Error Encountered with ExpSine2Kernel

### ISSUE THREAD

**Issue by Arjun94kh** [dfm/george#32]
When I use the ExpSine2Kernel, I get the following linear algebra error:

---

Traceback (most recent call last):
  File "kernelissue.py", line 9, in <module>
    gp.compute(t)
  File "/Library/Python/2.7/site-packages/george-0.2.0-py2.7-macosx-10.9-intel.egg/george/gp.py", line 178, in compute
    self.solver.compute(self._x, self._yerr, **kwargs)
  File "/Library/Python/2.7/site-packages/george-0.2.0-py2.7-macosx-10.9-intel.egg/george/basic.py", line 23, in compute
    self._factor = (cholesky(K, overwrite_a=True, lower=False), False)
  File "/Library/Python/2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 81, in cholesky
    check_finite=check_finite)
  File "/Library/Python/2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
## numpy.linalg.linalg.LinAlgError: 28-th leading minor not positive definite

Here's a sample program which gives this error:

---

from george import kernels
import george
import numpy as np

t = np.linspace(39.0, 65.0, 71)

gp = george.GP(kernels.ExpSine2Kernel(1, 1))
## gp.compute(t)

I tried using other hyperparameters for the kernel and got the same error.

**Comment by LuisaMaria** [comment]
I got the same error in a similar situation. I think it's connected to the entity of the error you put, as less you put as more frequently I get this error. Can we fix it please? I really need it.

**Comment by dfm** [comment]
This will always happen if you don't provide a diagonal term. It's a numerical issue with every linear algebra library. If you don't already have uncertainties to add along the diagonal, try just adding some small number: `gp.compute(t, 1e-8)`, for example.
