### ISSUE TITLE
Required library HODLR not found. Check the documentation for solutions.

### ISSUE THREAD

**Issue by andyyuan78** [dfm/george#34]
ubgpu@ubgpu:~/github/george$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing george.egg-info/PKG-INFO
writing top-level names to george.egg-info/top_level.txt
writing dependency_links to george.egg-info/dependency_links.txt
writing pbr to george.egg-info/pbr.json
reading manifest file 'george.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'hodlr/header/*.hpp'
writing manifest file 'george.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Found Eigen version 3.2.0 in: /usr/include/eigen3
Traceback (most recent call last):
  File "setup.py", line 177, in <module>
    "Programming Language :: Python",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 88, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 21, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/lib/python2.7/dist-packages/Pyrex/Distutils/build_ext.py", line 82, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 99, in build_extension
    raise RuntimeError("Required library HODLR not found. "
RuntimeError: Required library HODLR not found. Check the documentation for solutions.
ubgpu@ubgpu:~/github/george$

**Comment by dfm** [comment]
Did you check the documentation? What did you try and what didn't you try? 

You can't submit an issue like this without explanation.

**Comment by andyyuan78** [comment]
sorry, just i
