### ISSUE TITLE
George throwing error on import

### ISSUE THREAD

**Issue by MartynBrake** [dfm/george#67]
Hello,
Hopefully small error, but can not find a solution. 
But have installed george, successfully from git, but get following error when import:

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import george
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "george/__init__.py", line 17, in <module>
    from . import kernels
  File "george/kernels.py", line 26, in <module>
    from .kernel_interface import KernelInterface
ImportError: No module named kernel_interface

This is running on Ubuntu 14.04.1 LTS

Any help would be appreciated.

Thanks,
Martyn

**Comment by MartynBrake** [comment]
Hi,
Found the problem (from a previous issue - should have read those first!)

Was running python (then import) from the source code folder.

cd ~, then python and import and all is ok.

Sorry - monday and not enough coffee.

Martyn
