### ISSUE TITLE
issue using the HODLR solver

### ISSUE THREAD

**Issue by mrtommyb** [dfm/george#92]
My code runs fine when I use the basic solver but when I switch to HODLR I get the following errors

```
Traceback (most recent call last):
  File "run_epic.py", line 263, in <module>
    sampler = main(runmpi=False,nw=50,th=8,bi=1,fr=1,use_hodlr=True)
  File "run_epic.py", line 219, in main
    storechain=False)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/interruptible_pool.py", line 94, in map
    return r.get(self.wait_timeout)
  File "/home/tom/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'BaseConstantKernel' object has no attribute 'a'
```

**Comment by mrtommyb** [comment]
I get the following

```
emcee: Exception while calling your likelihood function:
  params: [  8.05968308e-03   1.09724347e-07   6.69878165e-01   9.04338443e-02
  -2.81951304e-02  -8.74583097e+00  -6.28389294e+00   1.36384009e+02
   6.24672396e+00   9.01405884e-01   2.07892103e-02   6.93080622e-04
  -6.55108526e-05   4.36592258e+00   3.69807255e+00   2.30704023e+00
   3.38235091e+00  -3.94200085e+00   1.39223002e-01]
  args: [1, 0.0073000000000000001, 0.0001, True, 0.6698388457298279, 0.8, 0.09085439145565033, 0.8, False, array([  3.60951412e-04,  -5.38591107e-05,  -2.73110365e-04, ...,
        -1.55637998e-04,  -3.57024603e-05,   2.23436610e-04]), array([ 0.00027646,  0.00027667,  0.00027693, ...,  0.00028441,
        0.0002847 ,  0.00028393]), array([ 0.]), array([  120.55986443,   120.58029872,   120.60073322, ...,  1590.9405163 ,
        1590.96095071,  1591.00181954]), array([ 0.01881134,  0.01881134,  0.01881134, ...,  0.01881134,
        0.01881134,  0.01881134]), array([ 0.]), array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]]), array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]]), array([ 0.,  0.,  0., ...,  0.,  0.,  0.]), array([ 1208.86670891,  1266.71041653,  1267.70865078,  1268.7069835 ,
        1271.68968502,  1275.69264679,  1300.86443801,  1358.7085874 ,
        1382.63282948]), array([ 113.92,   21.31,  -24.61,  -45.59,   67.27,  -25.59,   -9.1 ,
         96.36,    0.  ]), array([ 24.31,  17.52,  19.74,  16.88,  18.45,  25.04,  27.11,  18.44,
        14.93]), array([ 0.02083333,  0.02083333,  0.02083333,  0.02083333,  0.02083333,
        0.02083333,  0.02083333,  0.02083333,  0.02083333]), 2, './', False, 500, True]
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/tom/gitcode/redgiantGP2/code/transitemcee_EPIC_logpriors.py", line 450, in logchi2_rv_phaseGP2
    gp.compute(time[section], err_jit[section])
  File "/home/tom/anaconda3/lib/python3.6/site-packages/george/gp.py", line 305, in compute
    self.solver = self.solver_type(self.kernel, **(self.solver_kwargs))
  File "/home/tom/anaconda3/lib/python3.6/site-packages/george/kernels.py", line 65, in __getattr__
    return getattr(self.models[None], name)
AttributeError: 'BaseConstantKernel' object has no attribute 'a'
Traceback (most recent call last):
  File "run_epic.py", line 263, in <module>
    sampler = main(runmpi=False,nw=50,th=1,bi=1,fr=1,use_hodlr=True)
  File "run_epic.py", line 219, in main
    storechain=False)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/tom/anaconda3/lib/python3.6/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/tom/gitcode/redgiantGP2/code/transitemcee_EPIC_logpriors.py", line 450, in logchi2_rv_phaseGP2
    gp.compute(time[section], err_jit[section])
  File "/home/tom/anaconda3/lib/python3.6/site-packages/george/gp.py", line 305, in compute
    self.solver = self.solver_type(self.kernel, **(self.solver_kwargs))
  File "/home/tom/anaconda3/lib/python3.6/site-packages/george/kernels.py", line 65, in __getattr__
    return getattr(self.models[None], name)
AttributeError: 'BaseConstantKernel' object has no attribute 'a'
```

**Comment by dfm** [comment]
I'm not sure there then. Can you send a minimal snippet of code that reproduces this behavior.

**Comment by mrtommyb** [comment]
Yes, here
```
import numpy as np
import george
from george.kernels import ExpSquaredKernel

flux = np.random.normal(size=1000)
model_lc = np.zeros_like(flux)
time = np.arange(1000)
err = 1.0
hp1 = 1.6E-4
hp2 = 0.0032

resid = flux - model_lc

kernel = (hp1**2 * ExpSquaredKernel(hp2))
gp = george.GP(kernel, solver=george.HODLRSolver)
gp.compute(time, err)
```

**Comment by dfm** [comment]
Works fine for me! Can you try uninstalling and updating george?

**Comment by mrtommyb** [comment]
i just reinstalled from source

**Comment by mrtommyb** [comment]
Actually, I take that back. I uninstalled and installed using 
```
pip install -e .
```

and it seems to have cleared things up

**Comment by dfm** [comment]
Ok great!

**Comment by mrtommyb** [comment]
Sorry to be a bother!
